In [5]:
%pip install opencv-python

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


How To read Picture from  the user

In [ ]:
import cv2
img=cv2.imread("Sachin pic.jpg",1)  #There are three channel of colour 0,1,-1 and all these channel change the colour of pic
print(img)                          #It will print the matrix of the picture
cv2.imshow('Frame',img)
cv2.waitKey(0)
cv2.destroyAllWindows


How to read video from the web cam

In [7]:
import cv2
cap=cv2.VideoCapture(0)
while(True):
    ret,frame=cap.read()            #ret it will tell whether frame is detected or not and frame will store the value of reading frame
    cv2.imshow('frame',frame)       #it will take two parameter first one is frame name and second one is which frame i have to show
    if cv2.waitKey(1) & 0XFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

How to read gray scale video from the web cam

In [ ]:
import cv2
cap=cv2.VideoCapture(0)
while(True):
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #converting the frame into gray scale and it take two parameter

    cv2.imshow('Video',gray)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
    

How to save Video from the camera

In [8]:
import cv2
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')  
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))

while True:
    ret, frame = cap.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #converting the frame into gray scale and it take two parameter
    if ret:
        out.write(frame)
        cv2.imshow('frame', gray)               #It will show the gray the video in the gray colour
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()  


How to draw a line and rectangle on image

In [1]:
import numpy as np
import cv2
img=cv2.imread('test.jpg',0) #if we did't give second parameter then it will load default
print(img)
img=cv2.line(img,(0,0),(255,255),(255,0,0),4) #it will draw a line on image and it take four argumant (name of image,startig point,ending point,thickness)
img=cv2.arrowedLine(img,(155,0),(255,263),(255,0,0),4) #it will draw a line on image and it take four argumant (name of image,startig point,ending point,thickness) it will draw arrow line
img=cv2.rectangle(img,(384,0),(510,128),(0,0,255),1) #it will draw a rectangel last one is thickness if we use -1 it will fill the rectangle
font=cv2.FONT_HERSHEY_COMPLEX
#img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
cv2.imshow('frame',img)
cv2.waitKey()
cv2.destroyAllWindows

<>:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
<>:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?


[[239 239 238 ... 220 220 222]
 [240 239 239 ... 218 218 220]
 [239 239 238 ... 220 220 221]
 ...
 [ 95  97 101 ... 142 150 158]
 [ 98 104 107 ... 144 154 159]
 [ 98 104 107 ... 144 154 159]]


C:\Users\Sachin chaurasiya\AppData\Local\Temp\ipykernel_13424\2860205131.py:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
C:\Users\Sachin chaurasiya\AppData\Local\Temp\ipykernel_13424\2860205131.py:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
C:\Users\Sachin chaurasiya\AppData\Local\Temp\ipykernel_13424\2860205131.py:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)
C:\Users\Sachin chaurasiya\AppData\Local\Temp\ipykernel_13424\2860205131.py:9: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  img=cv2.putText('img','opencv'(10,500),font,4,(255,255,255),10,cv2.LINE_AA)


TypeError: 'str' object is not callable

How to reset the frame size in Open cv

In [1]:
import cv2
cap=cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_TYPE))
cap.set(3,1200)
cap.set(4,1200)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_TYPE))
while True:
    ret,frame=cap.read()
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows
    
    

640.0
-1.0
1280.0
-1.0


<function destroyAllWindows>